osqp: Version pin to <1.0 for now
    File "/home/runner/work/qpsolvers/qpsolvers/qpsolvers/solvers/osqp_.py", line 137, in osqp_solve_problem
      success_status = osqp.constant("OSQP_SOLVED")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  TypeError: constant() missing 1 required positional argument: 'algebra'